name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test SSH Connection
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "✅ SSH connection successful!"
          whoami
          pwd

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/airbureau
          
          echo "🛑 Stopping bybit-linear-ticker service..."
          sudo systemctl stop bybit-linear-ticker.service || true
          
          echo "📥 Pulling latest code..."
          git pull origin main
          
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
          echo "🔄 Reloading systemd..."
          sudo systemctl daemon-reload
          
          echo "🚀 Starting bybit-linear-ticker service..."
          sudo systemctl start bybit-linear-ticker.service
          sudo systemctl enable bybit-linear-ticker.service
          
          sleep 5
          
          echo "✅ Checking service status..."
          sudo systemctl status bybit-linear-ticker.service --no-pager
          
          echo "📋 Checking recent logs..."
          sudo journalctl -u bybit-linear-ticker.service --since "1 minute ago" --no-pager
          
          echo "🎉 Deployment completed successfully!"