name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ci-deploy
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}

        script: |
          echo "🚀 Starting deployment process..."
          
          # Информация о сервере
          echo "📊 Server Info:"
          echo "   Hostname: $(hostname)"
          echo "   User: $(whoami)"
          echo "   Directory: $(pwd)"
          
          cd /opt/airbureau
          echo "📁 Project directory: $(pwd)"
          
          # Останавливаем сервис
          echo "🛑 Stopping bybit-linear-ticker service..."
          sudo systemctl stop bybit-linear-ticker.service || echo "Service was not running"
          
          # Обновляем код
          echo "📥 Pulling latest code..."
          git pull origin main
          
          # Настраиваем виртуальное окружение
          echo "🐍 Setting up Python environment..."
          if [ ! -d "venv" ]; then
            python3 -m venv venv
            echo "✅ Virtual environment created"
          fi
          
          source venv/bin/activate
          pip install --upgrade pip
          echo "📦 Installing dependencies..."
          pip install -r requirements.txt
          
          # Обновляем systemd
          echo "🔄 Reloading systemd..."
          sudo systemctl daemon-reload
          
          # Запускаем сервис
          echo "🚀 Starting bybit-linear-ticker service..."
          sudo systemctl start bybit-linear-ticker.service
          sudo systemctl enable bybit-linear-ticker.service
          
          # Ждем запуска
          echo "⏳ Waiting for service to start..."
          sleep 10
          
          # Проверяем статус
          echo "✅ Checking service status..."
          sudo systemctl status bybit-linear-ticker.service --no-pager
          
          # Проверяем логи
          echo "📋 Checking service logs..."
          sudo journalctl -u bybit-linear-ticker.service --since "1 minute ago" --no-pager -n 20
          
          echo "🎉 Deployment completed successfully!"